#!/usr/bin/env bash
#
# Example parameters:
#   api:2
#   args:task 4 modify new-task-description
#   command:modify
#   rc:/path/to/taskwarrior/rc/.taskrc
#   data:/path/to/taskwarrior/data/directory
#   version:2.5.3
#
# Example stdin:
#   {"description":"new-task-description","entry":"20210915T072256Z","modified":"20210915T143806Z","status":"pending","uuid":"7c07894f-f774-4858-af3f-ca60dd3508fd"}
#

COMMAND=$(echo "$2" | cut -f2- -d:)
GIT_REPO=$(dirname "$(echo "$5" | cut -f2 -d:)")
CONTEXT=""  # Command context info from task command.
TASK="<None>"  # Current task descriptions, if exists.

for i in "$@"; do
    CONTEXT="${CONTEXT}${i}\n"
done

# Append more context info to commit message.
CONTEXT="${CONTEXT}host:$(uname -n)\n"
CONTEXT="${CONTEXT}date:$(date +%FT%T)\n"

# Full task data with JSON format.
while IFS= read -r DATA
do
    echo "$DATA" > /dev/null
done < /dev/stdin

LOG_FILE="${GIT_REPO}/git-sync.log"

function _log() {
    # Debug:
    # echo -e "$1" | tee -a "${LOG_FILE}"
    echo -e "$1" >> "${LOG_FILE}"
}

if [[ -n "$DATA" ]]; then
    if ! command -v jq > /dev/null; then
        echo "jq is required"
        exit 1
    fi

    # Read task description from JSON data.
    TASK=$(echo "$DATA" | jq .description)
fi

_log "${CONTEXT}\nTask:\n${TASK}\n"


# Prepare to check the git repo status and commit.

git -C "${GIT_REPO}" diff --exit-code HEAD >/dev/null 2>&1 
DIFF_RESULT=$?

if [[ $DIFF_RESULT -eq 0 ]]; then
    _log "No changes found this time, skip to commit."
    exit 0
fi

_log "Committing and pushing..."

# Commit changes to git repository.
git -C "${GIT_REPO}" commit -a -m "${COMMAND}" >/dev/null 2>&1

# Now let's use git-sync in background.
(cd "${GIT_REPO}" && sh git-sync) &>>"${LOG_FILE}" & disown
